/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author MultiRepair
 */
public class CargarInmueble extends javax.swing.JFrame {

    /**
     * Creates new form CargarInmueble
     */
    public CargarInmueble() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorCargarInmueble = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        botonVolverCargarInmuble = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        botonCargarInmuebleCasa = new javax.swing.JButton();
        botonVerInmuebleDepartamento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        contenedorCargarInmueble.setBackground(new java.awt.Color(255, 255, 255));
        contenedorCargarInmueble.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 134, 190));

        botonVolverCargarInmuble.setBackground(new java.awt.Color(0, 134, 190));
        botonVolverCargarInmuble.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        botonVolverCargarInmuble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arrow_left_2.png"))); // NOI18N
        botonVolverCargarInmuble.setMnemonic('\u0006');
        botonVolverCargarInmuble.setText("  Volver");
        botonVolverCargarInmuble.setBorder(null);
        botonVolverCargarInmuble.setBorderPainted(false);
        botonVolverCargarInmuble.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVolverCargarInmuble.setMargin(new java.awt.Insets(0, 0, 0, 0));
        botonVolverCargarInmuble.setMaximumSize(new java.awt.Dimension(179, 129));
        botonVolverCargarInmuble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonVolverCargarInmubleMouseClicked(evt);
            }
        });
        botonVolverCargarInmuble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverCargarInmubleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(botonVolverCargarInmuble, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(660, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonVolverCargarInmuble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        contenedorCargarInmueble.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 800, 60));

        jPanel3.setBackground(new java.awt.Color(0, 134, 190));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jLabel2.setText("CARGAR INMUEBLE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(jLabel2)
                .addContainerGap(287, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(14, 14, 14))
        );

        contenedorCargarInmueble.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 60));

        botonCargarInmuebleCasa.setBackground(new java.awt.Color(0, 134, 190));
        botonCargarInmuebleCasa.setFont(new java.awt.Font("Roboto Light", 1, 20)); // NOI18N
        botonCargarInmuebleCasa.setText("Cargar Casa");
        botonCargarInmuebleCasa.setBorder(null);
        botonCargarInmuebleCasa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonCargarInmuebleCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarInmuebleCasaActionPerformed(evt);
            }
        });
        contenedorCargarInmueble.add(botonCargarInmuebleCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 280, 50));

        botonVerInmuebleDepartamento.setBackground(new java.awt.Color(0, 134, 190));
        botonVerInmuebleDepartamento.setFont(new java.awt.Font("Roboto Light", 1, 20)); // NOI18N
        botonVerInmuebleDepartamento.setText("Cargar Departamento");
        botonVerInmuebleDepartamento.setBorder(null);
        botonVerInmuebleDepartamento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonVerInmuebleDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerInmuebleDepartamentoActionPerformed(evt);
            }
        });
        contenedorCargarInmueble.add(botonVerInmuebleDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 280, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorCargarInmueble, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorCargarInmueble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverCargarInmubleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVolverCargarInmubleMouseClicked

    }//GEN-LAST:event_botonVolverCargarInmubleMouseClicked

    private void botonVolverCargarInmubleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverCargarInmubleActionPerformed
        this.hide();
        Inmuebles h = new Inmuebles();
        h.setVisible(true);
    }//GEN-LAST:event_botonVolverCargarInmubleActionPerformed

    private void botonCargarInmuebleCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarInmuebleCasaActionPerformed
        CargarCasa a = new CargarCasa();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonCargarInmuebleCasaActionPerformed

    private void botonVerInmuebleDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerInmuebleDepartamentoActionPerformed
        CargarDepartamento a = new CargarDepartamento();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonVerInmuebleDepartamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargarInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargarInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargarInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargarInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CargarInmueble().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCargarInmuebleCasa;
    private javax.swing.JButton botonVerInmuebleDepartamento;
    private javax.swing.JButton botonVolverCargarInmuble;
    private javax.swing.JPanel contenedorCargarInmueble;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
