/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.*;
import javax.swing.JOptionPane;

/**
 *
 * @author MultiRepair
 */
public class CargarCasa extends javax.swing.JFrame {

    /**
     * Creates new form CargarCasa
     */
    public CargarCasa() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorCargarCasa = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        botonVolverCargarCasa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        direccionCasa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        valorTasacionCasa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        metrosCuadradosCubiertosCasa = new javax.swing.JTextField();
        cantidadAmbientesCasa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        metrosCuadradosTotalesCasa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        antiguedadCasa = new javax.swing.JTextField();
        botonCargarDatosCasa = new javax.swing.JButton();
        dniCasa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        contenedorCargarCasa.setBackground(new java.awt.Color(255, 255, 255));
        contenedorCargarCasa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 134, 190));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jLabel2.setText("CARGAR CASA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(317, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(313, 313, 313))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        contenedorCargarCasa.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 60));

        jPanel3.setBackground(new java.awt.Color(0, 134, 190));

        botonVolverCargarCasa.setBackground(new java.awt.Color(0, 134, 190));
        botonVolverCargarCasa.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        botonVolverCargarCasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arrow_left_2.png"))); // NOI18N
        botonVolverCargarCasa.setMnemonic('\u0006');
        botonVolverCargarCasa.setText("  Volver");
        botonVolverCargarCasa.setBorder(null);
        botonVolverCargarCasa.setBorderPainted(false);
        botonVolverCargarCasa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVolverCargarCasa.setMargin(new java.awt.Insets(0, 0, 0, 0));
        botonVolverCargarCasa.setMaximumSize(new java.awt.Dimension(179, 129));
        botonVolverCargarCasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonVolverCargarCasaMouseClicked(evt);
            }
        });
        botonVolverCargarCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverCargarCasaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(botonVolverCargarCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(660, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonVolverCargarCasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        contenedorCargarCasa.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 800, 60));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Direccion:");
        contenedorCargarCasa.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 90, -1));

        direccionCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionCasaActionPerformed(evt);
            }
        });
        contenedorCargarCasa.add(direccionCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 190, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Valor tasacion:");
        contenedorCargarCasa.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        valorTasacionCasa.setToolTipText("");
        contenedorCargarCasa.add(valorTasacionCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 190, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Metros cuadrados cubiertos:");
        contenedorCargarCasa.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 250, -1));
        contenedorCargarCasa.add(metrosCuadradosCubiertosCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 190, -1));

        cantidadAmbientesCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadAmbientesCasaActionPerformed(evt);
            }
        });
        contenedorCargarCasa.add(cantidadAmbientesCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 190, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Cantidad Ambientes:");
        contenedorCargarCasa.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, 20));

        metrosCuadradosTotalesCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metrosCuadradosTotalesCasaActionPerformed(evt);
            }
        });
        contenedorCargarCasa.add(metrosCuadradosTotalesCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 190, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Metros cuadrados totales:");
        contenedorCargarCasa.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Antiguedad: ");
        contenedorCargarCasa.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, -1));

        antiguedadCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antiguedadCasaActionPerformed(evt);
            }
        });
        contenedorCargarCasa.add(antiguedadCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 190, -1));

        botonCargarDatosCasa.setBackground(new java.awt.Color(0, 134, 190));
        botonCargarDatosCasa.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        botonCargarDatosCasa.setForeground(new java.awt.Color(0, 0, 0));
        botonCargarDatosCasa.setText("CARGAR DATOS");
        botonCargarDatosCasa.setBorder(null);
        botonCargarDatosCasa.setBorderPainted(false);
        botonCargarDatosCasa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCargarDatosCasa.setMargin(new java.awt.Insets(0, 0, 0, 0));
        botonCargarDatosCasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCargarDatosCasaMouseClicked(evt);
            }
        });
        botonCargarDatosCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarDatosCasaActionPerformed(evt);
            }
        });
        contenedorCargarCasa.add(botonCargarDatosCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, 140, 40));

        dniCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniCasaActionPerformed(evt);
            }
        });
        contenedorCargarCasa.add(dniCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 190, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Dni de la persona:");
        contenedorCargarCasa.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorCargarCasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorCargarCasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverCargarCasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVolverCargarCasaMouseClicked

    }//GEN-LAST:event_botonVolverCargarCasaMouseClicked

    private void botonVolverCargarCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverCargarCasaActionPerformed
        this.hide();
        CargarInmueble h = new CargarInmueble();
        h.setVisible(true);
    }//GEN-LAST:event_botonVolverCargarCasaActionPerformed

    private void direccionCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionCasaActionPerformed

    private void botonCargarDatosCasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCargarDatosCasaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCargarDatosCasaMouseClicked

    private void botonCargarDatosCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarDatosCasaActionPerformed

        try {
            String dni = dniCasa.getText();

            LecturaArchivoInmueble m = new LecturaArchivoInmueble();
            m.cargarCasa();

            int i = m.controlPropiedad(dni);

            if (i == 1) {
                JOptionPane.showMessageDialog(rootPane, "El dni ya se encuentra cargado");
            } else {
                CargaDatosInmueble a = new CargaDatosInmueble();

                String direccion = direccionCasa.getText();
                double tasacionCasa = Double.parseDouble(valorTasacionCasa.getText());
                int ambientesCasa = Integer.parseInt(cantidadAmbientesCasa.getText());
                double metrosCubiertos = Double.parseDouble(metrosCuadradosCubiertosCasa.getText());
                double metrosTotales = Double.parseDouble(metrosCuadradosTotalesCasa.getText());
                int antiguedad = Integer.parseInt(antiguedadCasa.getText());

                a.cargaArchivoCasa(dni, antiguedad, direccion, tasacionCasa, ambientesCasa, metrosCubiertos, metrosTotales);

                JOptionPane.showMessageDialog(rootPane, "El inmueble se cargo exitosamente");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Ingreso un dato mal");
        }
    }//GEN-LAST:event_botonCargarDatosCasaActionPerformed

    private void cantidadAmbientesCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadAmbientesCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadAmbientesCasaActionPerformed

    private void dniCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniCasaActionPerformed

    private void metrosCuadradosTotalesCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metrosCuadradosTotalesCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_metrosCuadradosTotalesCasaActionPerformed

    private void antiguedadCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antiguedadCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_antiguedadCasaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargarCasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargarCasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargarCasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargarCasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CargarCasa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField antiguedadCasa;
    private javax.swing.JButton botonCargarDatosCasa;
    private javax.swing.JButton botonVolverCargarCasa;
    private javax.swing.JTextField cantidadAmbientesCasa;
    private javax.swing.JPanel contenedorCargarCasa;
    private javax.swing.JTextField direccionCasa;
    private javax.swing.JTextField dniCasa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField metrosCuadradosCubiertosCasa;
    private javax.swing.JTextField metrosCuadradosTotalesCasa;
    private javax.swing.JTextField valorTasacionCasa;
    // End of variables declaration//GEN-END:variables
}
